<a href="https://colab.research.google.com/github/nholea/Curso-Python3/blob/main/Tarea32.%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 15 - Módulos de Python: numpy

## Ejercicio 1


Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la
shape antes y después del reshape.

In [1]:
import numpy as np

In [9]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("d1 =", d1)
print("Dimensión:", d1.ndim)
print("Shape:", d1.shape)

d3 = d1.reshape(3,1,3)
print("d3 =", d3)
print("Dimensión:", d3.ndim)
print("Shape:", d3.shape)


d1 = [1 2 3 4 5 6 7 8 9]
Dimensión: 1
Shape: (9,)
d3 = [[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
Dimensión: 3
Shape: (3, 1, 3)


## Ejercicio 2


Dados los arrays 2D [[-6, -5], [-4, -3], [-2, -1]] y [[1, 2], [3, 4], [5, 6]], concaténalos de
modo que obtengas el array [[1, 2, -6, -5], [3, 4, -4, -3] [5, 6, -2, -1]].

In [14]:
x = np.array([[-6, -5], [-4, -3], [-2, -1]])
y = np.array( [[1, 2], [3, 4], [5, 6]])

xy = np.concatenate((y,x), axis=1)
print("Array resultado:\n", xy)


Array resultado:
 [[ 1  2 -6 -5]
 [ 3  4 -4 -3]
 [ 5  6 -2 -1]]


## Ejercicio 3

Dado el array 2D [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]], divídelo en 3 arrays 2D

In [19]:
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])

b1, b2, b3 = np.array_split(a, 3)
print("Del array original a =\n", a)
print("Dividiéndolo en 3 obtenemos:")
print("1º\n", b1)
print("2º\n", b2)
print("3º\n", b3)


Del array original a =
 [[ 1  2  3]
 [-1  0  1]
 [ 4  5  6]
 [-4  0  4]
 [ 3  2  1]
 [-3  0  3]]
Dividiéndolo en 3 obtenemos:
1º
 [[ 1  2  3]
 [-1  0  1]]
2º
 [[ 4  5  6]
 [-4  0  4]]
3º
 [[ 3  2  1]
 [-3  0  3]]


## Ejercicio 4

Dado el array 2D [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
"elle"]], busca las palabras que sean palíndromos.
PISTA: Necesitarás una función universal

In [22]:
a = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])

def is_palind(word):
    words = []
    isPalind = True
    for i in word.lower():
        words.append(i)
    n = len(words)
    for i in range(int(n / 2)):
        if words[i] != words[n - (i + 1)]:
            isPalind = False
    return isPalind

is_palind = np.frompyfunc(is_palind, 1, 1)
b = np.where(is_palind(a) == True)

print("Las palabras palíndromas son: ")
for i in range(len(b[0])):
    print(a[b[0][i], b[1][i]])


Las palabras palíndromas son: 
ala
kayak
elle


## Ejercicio 5

Dado el array 1D ["cena", "frío", "kayak", "remo", "sol"]], ¿qué índice deberá ocupar el elemento
“python” para que se mantenga el orden alfabético?

In [23]:
a = np.array(["cena", "frío", "kayak", "remo", "sol"])
b = np.searchsorted(a, "python")

print("El elemento python deberá ocupar el índice", b)



El elemento python deberá ocupar el índice 3


## Ejercicio 6

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número
del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!!
Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase
“¡Has fallado! ¡Prueba otra vez!”


In [25]:
from numpy import random

In [27]:
rand_num = random.randint(1,10)

print("Adivina el número aleatorio: ")
num = int(input())
count = 1

while num != rand_num:
    print("“¡Has fallado! ¡Prueba otra vez!”")
    num = int(input())
    count += 1

print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {} y sólo te ha costado {} intentos".format(rand_num, count))


Adivina el número aleatorio: 
4
“¡Has fallado! ¡Prueba otra vez!”
8
“¡Has fallado! ¡Prueba otra vez!”
6
“¡Has fallado! ¡Prueba otra vez!”
1
“¡Has fallado! ¡Prueba otra vez!”
2
“¡Has fallado! ¡Prueba otra vez!”
3
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 3 y sólo te ha costado 6 intentos


## Ejercicio 7

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros
entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá
que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El
juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente.
Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:
{}”


In [36]:
from numpy.lib.arraysetops import unique
rand_array = random.randint(20, size=5)
print(rand_array)
value = 0
position = 0

while position !=5:
    nums = []
    value = 0
    position = 0
    for i in range(5):
       num = int(input("Introduce el elemento en la posición {} ".format(i)))
       nums.append(num)
       if num in rand_array:
           value +=1

       if num == rand_array[i]:
            position +=1

    nums_np = np.array(nums)
    unique_sol, count_sol = np.unique(nums_np, return_counts=True)
    unique_nums, count_nums = np.unique(rand_array, return_counts=True)

    for i in unique_sol:
        if i in unique_nums:
            idx_element = np.where(unique_sol == i)[0][0]
            idx_nums = np.where(unique_nums == i)[0][0]
            if count_sol[idx_element] > count_nums[idx_nums]:
                value -= count_sol[idx_element] - count_nums[idx_nums]

    print("Tu respuesta ha sido", nums)
    print("Has acertado",  value, "valores")
    print("Has acertado", position, "posiciones")
    nums.clear()

print("¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:",rand_array)
       
        


[ 5 17  8 14 16]
Introduce el elemento en la posición 0 17
Introduce el elemento en la posición 1 8
Introduce el elemento en la posición 2 14
Introduce el elemento en la posición 3 14
Introduce el elemento en la posición 4 16
Tu respuesta ha sido [17, 8, 14, 14, 16]
Has acertado 4 valores
Has acertado 2 posiciones
Introduce el elemento en la posición 0 5
Introduce el elemento en la posición 1 17
Introduce el elemento en la posición 2 8
Introduce el elemento en la posición 3 14
Introduce el elemento en la posición 4 16
Tu respuesta ha sido [5, 17, 8, 14, 16]
Has acertado 5 valores
Has acertado 5 posiciones
¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: [ 5 17  8 14 16]


## Ejercicio 8

A partir de la lista [-3, -2, -1, 0, 1, 2, 3], genera dos arrays aleatorios 2D de size = (3, 4) y
súmalos.

In [48]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])

x1 = random.choice(x, size= (3,4))
x2 = random.choice(x, size= (3,4))

result_sum = np.add(x1, x2)
print("El resultado de sumar los arrays aleatorios:\n {}\n\n {}\n\n es:\n\n {}".format(x1, x2, result_sum))

El resultado de sumar los arrays aleatorios:
 [[ 0  1  1  2]
 [-1  0 -3 -2]
 [ 0 -2  3 -2]]

 [[ 1 -3  0 -3]
 [-3  0  0  0]
 [ 2 -1 -2 -1]]

 es:

 [[ 1 -2  1 -1]
 [-4  0 -3 -2]
 [ 2 -3  1 -3]]


## Ejercicio 9

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.


In [57]:
def total_vowels(strings):
    count = 0
    for i in strings.lower():
        if i in "aeiou":
            count +=1
    return count

np_total_vowels = np.frompyfunc(total_vowels,1,1)






## Ejercicio 10

Crea una función universal que dados un array 1D de valores string y conjunto de strings, compruebe para
cada elemento del array 1D, si está presente o no en el conjunto

In [51]:
def is_in(string, set):
    if string in set:
        return True
    return False

np_is_in = np.frompyfunc(is_in,2,1)