<a href="https://colab.research.google.com/github/nholea/Curso-Python3/blob/main/Tarea10.%20Listas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 5 - Estructuras de datos: Listas





## Ejercicio 1


Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
finalmente muestre la secuencia invertida.


In [3]:
string = input("Introduzca una secuencia de caracteres: ")
l = []

print("=== Frase Original ===")
print(string)

for i in string:
    l.append(i)
l.reverse()

print("=== Frase Invertida ===")
for element in l:
    print(element, end = "")


Introduzca una secuencia de caracteres: Hola
=== Frase Original ===
Hola
=== Frase Invertida ===
aloH

## Ejercicio 2 



Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
mostrar el contenido de la lista.
Por ejemplo, si introducimos **hola caracola** y **adios marieta**, debería mostrarse **haodleao** **scamraarcioeltaa**.



In [4]:
str1 = input("Introduzca una secuencia de caracteres: ")
str2 = input("Introduce otra secuencia de caracteres: ")
l1 = []


if len(str1) == len(str2):
    for i in range(len(str1)):
        l1.append(str1[i])
        l1.append(str2[i])
    for element in l1:
        print(element, end = "")
else:
    print("Las 2 cadenas de caracteres no tienen el mismo tamaño.")
    


Introduzca una secuencia de caracteres: Hola Caracola
Introduce otra secuencia de caracteres: Adiós Marieta
HAodliaó sC aMraarcioeltaa

## Ejercicio 3 

Crea un programa que lea un string y guarde en una lista todas las consonantes.

In [5]:
str3 = input("Introduzca una secuencia de caracteres: ").lower()
vowels = ["a", "e", "i", "o", "u"]
letter = []

for i in str3:
    if i not in vowels:
        letter.append(i)
print(letter)

Introduzca una secuencia de caracteres: Hola caracola
['h', 'l', ' ', 'c', 'r', 'c', 'l']


## Ejercicio 4

Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.


In [10]:
word = list(input("Introduzca una palabra: ").lower())
palin = []

for i in word:
    palin.append(i)

palin.reverse()

if word == palin:
    print("La palabra introducida SÍ es un palíndromo")
else:
    print("La palabra introducida NO es un palíndromo")


Introduzca una palabra: CAMA
La palabra introducida NO es un palíndromo


## Ejercicio 5

Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

In [24]:
A=[]

for i in range(3):
    A.append([])
    for j in range(3):
        A[i].append(float(input("Introduce el elemento ({}, {}): ".format(i, j))))

print("\n=== Matriz 3x3 ===\n")

for i in range(3):
    for j in range(3):
        print(A[i][j], end = "  " if A[i][j] >= 0 else " " )
    print("")

print("")

for i in range(3):
    A[i].sort(reverse=True)
    print("El máximo de la fila {} es {}".format(i, A[i][0]))


Introduce el elemento (0, 0): 48
Introduce el elemento (0, 1): 56
Introduce el elemento (0, 2): 77
Introduce el elemento (1, 0): -20
Introduce el elemento (1, 1): -78
Introduce el elemento (1, 2): -4
Introduce el elemento (2, 0): 85
Introduce el elemento (2, 1): 45
Introduce el elemento (2, 2): 77

=== Matriz 3x3 ===

48.0  56.0  77.0  
-20.0 -78.0 -4.0 
85.0  45.0  77.0  

El máximo de la fila 0 es 77.0
El máximo de la fila 1 es -4.0
El máximo de la fila 2 es 85.0


## Ejercicio 6

Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición
debe contener su orden en la matriz (desde 0 hasta n
2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz

```
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
```








In [26]:
n = int(input("Introduce un número entero: "))
B = []

for i in range(n):
    B.append([])
    for j in range(n):
        B[i].append(n * i + j)

for i in range(n):
    print(B[i])


Introduce un número entero: 5
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[20, 21, 22, 23, 24]


## Ejercicio 7

Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada columna es el mismo valor.

In [44]:
n = int(input("Introduce el número de filas de la matriz: "))
m = int(input("Introduce el número de columnas de la matriz : "))
C = []
suma = []
sameSum = False

for i in range(n):
    C.append([])
    for j in range(m):
        C[i].append(float(input("Introduce el elemento ({}, {}): ".format(i, j))))

for i in range(n):
    for j in range(m):
        print(C[i][j], end = "  " if C[i][j] >= 0 else " " )
    print("")

for j in range(m):
    sum = 0
    for i in range(n):
        sum += C[i][j]
    suma.append(sum)

print(suma)

for i in range(m - 1):
    if suma[i] == suma[i + 1]:
        sameSum = True

print("¿La suma de cada columna es el mismo valor? {}".format("SÍ" if sameSum else "NO"))



        


Introduce el número de filas de la matriz: 3
Introduce el número de columnas de la matriz : 2
Introduce el elemento (0, 0): 1
Introduce el elemento (0, 1): 1
Introduce el elemento (1, 0): 1
Introduce el elemento (1, 1): 1
Introduce el elemento (2, 0): 1
Introduce el elemento (2, 1): 1
1.0  1.0  
1.0  1.0  
1.0  1.0  
[3.0, 3.0]
¿La suma de cada columna es el mismo valor? SÍ


## Ejercicio 8

Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos) se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

In [50]:
n = int(input("Introduce el número de filas de la matriz: "))
m = int(input("Introduce el número de columnas de la matriz : "))
D = []
identity = True

for i in range(n):
    D.append([])
    for j in range(m):
        D[i].append(float(input("Introduce el elemento ({}, {}): ".format(i, j))))

for i in range(n):
    for j in range(m):
        print(D[i][j], end = "  " if D[i][j] >= 0 else " " )
    print("")

if n == m:
    for i in range(n):
        for j in range(n):
            if i == j and D[i][j] != 1:
                identity = False
            if i != j and D[i][j] != 0:
                identity = False 
else:
    identity = False
    print("No es una matriz cuadrada. Debe tener mismo número de filas y columnas")

print("¿La matriz ingresada es la matriz identidad? {} ".format("SÍ" if identity else "NO"))


Introduce el número de filas de la matriz: 2
Introduce el número de columnas de la matriz : 2
Introduce el elemento (0, 0): 1
Introduce el elemento (0, 1): 0
Introduce el elemento (1, 0): 0
Introduce el elemento (1, 1): 1
1.0  0.0  
0.0  1.0  
¿La matriz ingresada es la matriz identidad? SÍ 


## Ejercicio 9

Realiza un programa que calcule la matriz transpuesta.

In [69]:
n = int(input("Introduce el número de filas de la matriz: "))
m = int(input("Introduce el número de columnas de la matriz : "))
F = []
T = []

for i in range(n):
    F.append([])
    for j in range(m):
        F[i].append(float(input("Introduce el elemento ({}, {}): ".format(i, j))))

print("\n === Matriz Introducida ===")
for i in range(n):
    for j in range(m):
        print(F[i][j], end = "  " if F[i][j] >= 0 else " " )
    print("")


print("\n === Matriz Traspuesta9 ===")
for i in range(m):
    T.append([])
    for j in range(n):
        T[i].append(F[j][i])

for i in range(n):
    for j in range(m):
        print(T[i][j], end = "  " if T[i][j] >= 0 else " " )
    print("")


Introduce el número de filas de la matriz: 3
Introduce el número de columnas de la matriz : 3
Introduce el elemento (0, 0): 9
Introduce el elemento (0, 1): 9
Introduce el elemento (0, 2): 8
Introduce el elemento (1, 0): 7
Introduce el elemento (1, 1): 6
Introduce el elemento (1, 2): 5
Introduce el elemento (2, 0): 4
Introduce el elemento (2, 1): 3
Introduce el elemento (2, 2): 2

 === Matriz Introducida ===
9.0  9.0  8.0  
7.0  6.0  5.0  
4.0  3.0  2.0  

 === Matriz Traspuesta9 ===
9.0  7.0  4.0  
9.0  6.0  3.0  
8.0  5.0  2.0  


## Ejercicio 10

Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
numpy.

In [59]:
import numpy as np

In [70]:
n = int(input("Introduce la dimensión de la matriz: "))

I = np.zeros((n,n))

for i in range(n):
    I[i, i] = 1

print("\n=== Matriz Identidad ===:\n{}".format(I))



Introduce la dimensión de la matriz: 4

=== Matriz Identidad ===:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
