<a href="https://colab.research.google.com/github/nholea/Curso-Python3/blob/main/Tarea12-Diccionarios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 6 - Estructuras de datos: Diccionarios

## Ejercicio 1


Crea un programa que pida un número entero positivo por teclado y que cree un diccionario cuyas claves
sean desde el número 1 hasta el número indicado. Los valores de cada clave serán las propias claves elevadas
al cubo.

In [7]:
num = int(input("Introduzca el número de claves del diccionario: "))
dicc = {}

for i in range(1, num + 1):
    dicc[i] = i ** 3

print(dicc)

Introduzca el número de claves del diccionario: 10
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


## Ejercicio 2


Escribe un programa que pregunte al usuario su nombre, edad y teléfono y lo guarde en un diccionario.
Después, debe mostrar por pantalla el mensaje ‘{nombre} tiene {edad} años y su número de teléfono es
{teléfono}.

In [9]:
agenda = {}
agenda["nombre"] = str(input("¿Cuál es su nombre?: "))
agenda["edad"] = int(input("¿Cuál es su edad?: "))
agenda["teléfono"] = int(input("¿Cuál es su teléfono de contacto?: "))

print("{} tiene {} años y su número de teléfono es {}".format(agenda["nombre"],agenda["edad"],agenda["teléfono"]))

¿Cuál es su nombre?: Natalia
¿Cuál es su edad?: 28
¿Cuál es su teléfono de contacto?: 6597763446
Natalia tiene 28 años y su número de teléfono es 6597763446


## Ejercicio 3

Escribe un programa que cree un diccionario simulando una cesta de la compra. El programa debe preguntar
el artículo y su precio por unidad. El artículo será la clave y el valor el precio, hasta que el usuario decida
terminar. Después se debe mostrar por pantalla la lista de la compra y el coste total, con el siguiente formato

Artículo 1 Precio
Artículo 2 Precio
Artículo 3 Precio
. . . . . .
Total Precio Total

In [17]:
cesta = {}
total = 0
key = input("Indica el artículo a añadir: ")

while key != "":
    cesta[key]= float(input("Introduzca el precio del artículo añadido: "))
    key = input("Indica el artículo a añadir: ")

for k, v in cesta.items():
    total += v
    print("|", k, v, "|")
print("." * 25)
print("Total", round(total,2))

Indica el artículo a añadir: Huevos
Introduzca el precio del artículo añadido: 2
Indica el artículo a añadir: Plátanos
Introduzca el precio del artículo añadido: 1.85
Indica el artículo a añadir: Barra Pan
Introduzca el precio del artículo añadido: 0.65
Indica el artículo a añadir: 
| Huevos 2.0 |
| Plátanos 1.85 |
| Barra Pan 0.65 |
.........................
Total 4.5


## Ejercicio 4

Crea un programa que lea números enteros hasta que introduzca el 0 y devuelva un diccionario con la
cantidad números positivos y negativos introducidos.

In [25]:

num = int(input("Introduzca un número entero: "))
positive = 0
negative = 0

while num != 0:
    if num < 0:
        negative +=1
    else:
        positive +=1
    num = int(input("Introduzca un número entero: "))

print({"Positivos":positive, "Negativos": negative})

Introduzca un número entero: -1
Introduzca un número entero: 4
Introduzca un número entero: -25
Introduzca un número entero: 9
Introduzca un número entero: 4
Introduzca un número entero: 9
Introduzca un número entero: -55
Introduzca un número entero: 0
{'Positivos': 4, 'Negativos': 3}


## Ejercicio 5

Crea un programa que lea números enteros hasta que introduzca el 0 y devuelva un diccionario con la
cantidad números pares e impares introducidos.


In [26]:
num = int(input("Introduzca un número entero: "))
even = 0
odd = 0

while num != 0:
    if num % 2 == 0:
        even +=1
    else:
        odd +=1
    num = int(input("Introduzca un número entero: "))

print({"Par":even, "Impar": odd})

Introduzca un número entero: 5
Introduzca un número entero: 6
Introduzca un número entero: 8
Introduzca un número entero: 8
Introduzca un número entero: 8
Introduzca un número entero: 3
Introduzca un número entero: 889
Introduzca un número entero: 291
Introduzca un número entero: 0
{'Par': 4, 'Impar': 4}


## Ejercicio 6

Crea un programa que permita al usuario introducir los nombres de los alumnos de una clase y las notas que
han obtenido. Cada alumno puede tener distinta cantidad de notas. Guarda la información en un diccionario
cuyas claves serán los nombres de los alumnos y los valores serán listas con las notas de cada alumno.

El programa va a pedir el nombre de un estudiante e irá pidiendo sus notas (del 1 al 10) hasta que introduzcamos un 0. Al final, cuando el nombre que introduzcamos sea un string vacío, el programa nos mostrará la
lista de alumnos y la nota media obtenida por cada uno de ellos.
PISTA: Vas a necesitar la función sum().

In [8]:
students = {}
student= str(input("Nombre alumno: "))
while student != "":
    students[student] = []
    notes = float(input("Introduce las notas obtenidas: "))
    while notes !=0:
        students[student].append(notes)
        notes = float(input("Introduce las notas obtenidas: "))
    student= str(input("Nombre alumno: "))

print("."*30)
for key, value in students.items():
    print(key, ":", round(sum(value)/len(value),2))

Nombre alumno: Natalia
Introduce las notas obtenidas: 8.75
Introduce las notas obtenidas: 5
Introduce las notas obtenidas: 7.55
Introduce las notas obtenidas: 9.99
Introduce las notas obtenidas: 10
Introduce las notas obtenidas: 0
Nombre alumno: Juan
Introduce las notas obtenidas: 5.75
Introduce las notas obtenidas: 6.25
Introduce las notas obtenidas: 10
Introduce las notas obtenidas: 9.25
Introduce las notas obtenidas: 0
Nombre alumno: 
..............................
Natalia : 8.26
Juan : 7.81


## Ejercicio 7

Crea un programa que pida un número entero positivo por teclado y que cree un diccionario cuyas claves
sean desde el número 1 hasta el número indicado. Los valores de cada clave serán tantos símbolos "*" como
indique la clave.


In [11]:
dicc = {}
num = int(input("Introduce la cantidad de claves del diccionario: "))

for i in range (1, num + 1):
    dicc[i] = "*" * i

print(dicc)

Introduce la cantidad de claves del diccionario: 10
{1: '*', 2: '**', 3: '***', 4: '****', 5: '*****', 6: '******', 7: '*******', 8: '********', 9: '*********', 10: '**********'}


## Ejercicio 8

Crea un programa que pida el número de palabras a introducir. Crear un diccionario de clave la palabra y
de valor la longitud de dicha palabra.

In [13]:
dicc = {}

word_amount = int(input("¿Cuántas palabras desea introducir?: "))
for i in range(word_amount):
    word = str(input("¿Qué palabra desea guardar en el diccionario?: "))
    dicc[word]=len(word)

print(dicc)


¿Cuántas palabras desea introducir?: 4
¿Qué palabra desea guardar en el diccionario?: Elefante
¿Qué palabra desea guardar en el diccionario?: Jirafa
¿Qué palabra desea guardar en el diccionario?: Koala
¿Qué palabra desea guardar en el diccionario?: Oso Panda
{'Elefante': 8, 'Jirafa': 6, 'Koala': 5, 'Oso Panda': 9}


## Ejercicio 9

Crea un programa que pida el número de palabras a introducir. Crear un diccionario de clave la palabra y
de valor el número de vocales de la palabra.

In [16]:
dicc = {}

word_amount = int(input("¿Cuántas palabras desea introducir?: "))
for i in range(word_amount):
    word = str(input("¿Qué palabra desea guardar en el diccionario?: ")).lower()
    vowels = 0
    for letter in word:
        if letter in "aeiou":
            vowels +=1
    dicc[word] = vowels
print(dicc)

¿Cuántas palabras desea introducir?: 4
¿Qué palabra desea guardar en el diccionario?: Elefante
¿Qué palabra desea guardar en el diccionario?: Jirafa
¿Qué palabra desea guardar en el diccionario?: Oso
¿Qué palabra desea guardar en el diccionario?: Gato
{'elefante': 4, 'jirafa': 3, 'oso': 2, 'gato': 2}


## Ejercicio 10

Dada una matriz, crea un diccionario que guarde el número de filas, el de columnas y cada fila en una entrada
de un diccionario.


In [21]:
import numpy as np

matrix = np.random.rand(5,4)

print("--------Matriz--------")
print(matrix)
print({"Filas": matrix.shape[0], "Columnas":matrix.shape[1]})

--------Matriz--------
[[0.73483117 0.88883235 0.04022398 0.24437807]
 [0.52310979 0.73628931 0.42994756 0.31080092]
 [0.78091438 0.30509826 0.92745369 0.19195389]
 [0.02894996 0.39231199 0.52981903 0.97214676]
 [0.49688717 0.19486647 0.53264567 0.67626216]]
{'Filas': 5, 'Columnas': 4}
